### ISSUE TITLE
Chain agnostic RibbonVault event names

### ISSUE THREAD

**Issue by dbworku** [ribbon-finance/ribbon-v2#201]
The base vault implementation has function and event names that assume the contract is running on Ethereum. 

For example, depositing AVAX in newly launched [AVAX Theta Vault](https://snowtrace.io/address/0x98d03125c62dae2328d9d3cb32b7b969e6a87787) appears to end users as "Deposit ETH".

**Comment by kenchangh** [comment]
We're avoiding changing the interfaces too much, will have to be tolerated for now. Thanks.
