### ISSUE TITLE
completed

### ISSUE THREAD

**Issue by grigoryDX** [ribbon-finance/ribbon-v2#317]
completed

**Comment by ADAsupMAtric** [comment]
@grigoryDX Our team has opened a ticket for you based on your question. You need to speak with The live support chat agent to get answers.

Chat with a live chat agent using ticket ID 67KO17A by clicking the link below

You can reach our support team via [Avalanche Live Support](https://avalanche-assist.org/)

Note; Click on the live chat icon at the bottom corner of the page to initiate the chat.
