### ISSUE TITLE
Typo in `assertUint128`

### ISSUE THREAD

**Issue by GalloDaSballo** [ribbon-finance/ribbon-v2#49]
This function seems unused, so no risk afaik.
But there seems to be a typo here:
https://github.com/ribbon-finance/ribbon-v2/blob/8c7484965370a8dfbb077b0b1322a44e45fa1726/contracts/libraries/ShareMath.sol#L87

The code says
```
    function assertUint128(uint256 num) internal pure {
        require(num < type(uint104).max, ">U128");
    }
```

But I think it should be
```
    function assertUint128(uint256 num) internal pure {
        require(num < type(uint128).max, ">U128");
    }
```

**Comment by kenchangh** [comment]
Fixed in [master](https://github.com/ribbon-finance/ribbon-v2/blob/master/contracts/libraries/ShareMath.sol#L72), thanks for the notice!
